# Generated by Django 2.0.6 on 2018-06-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerDesperdicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, max_length=60, null=True)),
                ('colaborador', models.CharField(blank=True, max_length=300, null=True)),
                ('evento', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'listener_desperdicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerHorasfrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, max_length=60, null=True)),
                ('colaborador', models.CharField(blank=True, max_length=300, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cc_ea', models.BooleanField()),
            ],
            options={
                'db_table': 'listener_horasfrente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=10, unique=True)),
                ('projeto', models.CharField(blank=True, max_length=60, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('id_jira', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'listener_issue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerIssuetypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'listener_issuetypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerKeyresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=2000, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'listener_keyresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, max_length=60, null=True)),
                ('limite', models.IntegerField()),
                ('tipo_limite', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'listener_limits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerLogjson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.CharField(blank=True, max_length=30000, null=True)),
            ],
            options={
                'db_table': 'listener_logjson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerMaillimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'listener_maillimits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, max_length=60, null=True)),
                ('quarter', models.CharField(blank=True, max_length=2, null=True)),
                ('ano', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'listener_objective',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerProjetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'listener_projetos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('transicao_origem', models.CharField(blank=True, max_length=50, null=True)),
                ('transicao_destino', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'listener_transition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerTransitionorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_fluxo', models.CharField(blank=True, max_length=30, null=True)),
                ('ordem', models.IntegerField()),
                ('transicao_destino', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'listener_transitionorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListenerValorhorames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'listener_valorhorames',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Desperdicio',
        ),
        migrations.DeleteModel(
            name='HorasFrente',
        ),
        migrations.DeleteModel(
            name='IssueTypes',
        ),
        migrations.RemoveField(
            model_name='keyresult',
            name='objective',
        ),
        migrations.RemoveField(
            model_name='logjson',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='maillimits',
            name='limit',
        ),
        migrations.DeleteModel(
            name='Projetos',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='issue',
        ),
        migrations.DeleteModel(
            name='TransitionOrder',
        ),
        migrations.DeleteModel(
            name='ValorHoraMes',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='KeyResult',
        ),
        migrations.DeleteModel(
            name='Limits',
        ),
        migrations.DeleteModel(
            name='LogJson',
        ),
        migrations.DeleteModel(
            name='MailLimits',
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
